name: taubermusik
favicon: null
layout_spectrum: 0.76522
typography_spectrum: 0.2207
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9deda'
    - '#11161c'
    - '#374643'
    - '#c87660'
    - '#853f35'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
